In [1]:
import yfinance as yf
blockinc = yf.download(
    tickers = 'XYZ', 
    start='2023-04-01', 
    end='2025-04-01'
    )
blockinc

YF.download() has changed argument auto_adjust default to True

[*********************100%***********************]  1 of 1 completed

Price           Close       High        Low       Open    Volume
Ticker            XYZ        XYZ        XYZ        XYZ       XYZ
Date
2023-04-03  67.830002  68.389999  65.805000  67.599998  16969800
2023-04-04  68.839996  69.739998  67.669998  68.260002  15229000
2023-04-05  67.660004  68.239998  66.620003  67.214996  11586700
2023-04-06  68.099998  69.029999  66.160004  66.800003  11359800
2023-04-10  66.360001  66.800003  65.470001  66.330002  11598900
...               ...        ...        ...        ...       ...
2025-03-25  61.330002  63.689999  61.209999  62.764999   7366100
2025-03-26  59.049999  61.360001  58.799999  60.889999   8947800
2025-03-27  56.990002  58.900002  56.880001  58.759998   7927100
2025-03-28  55.330002  57.000000  54.689999  56.540001  10692000
2025-03-31  54.330002  54.689999  52.250000  53.889999   8163700

[500 rows x 5 columns]